# Generated by Django 4.2.5 on 2023-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('talla', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('stock', models.CharField(choices=[('Disponible', 'DISPONIBLE'), ('No Disponible', 'NO DISPONIBLE'), ('Descontinuado', 'DESCONTINUADO')], max_length=15)),
            ],
        ),
    ]
