# Generated by Django 4.2.5 on 2023-11-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDemo', '0002_usuario_alter_producto_color_alter_producto_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='estado',
        ),
    ]
