# Generated by Django 4.2.5 on 2023-12-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDemo', '0003_rename_stock_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=16)),
                ('password2', models.CharField(max_length=16)),
            ],
        ),
    ]
