# Generated by Django 4.2.5 on 2023-12-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDemo', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
